---
development:
  cloud_name: "lusintoys"
  api_key: '829129926647766'
  api_secret: FQDLNL7g_yUnItOeb_1RRDxU5F4
  enhancmage_tag: true
  static_image_support: false
poduction:
  cloud_name: "lusintoys"
  api_key: '829129926647766'
  api_secret: FQDLNL7g_yUnItOeb_1RRDxU5F4
  enhance_image_tag: true
  tic_image_support: true
  secure: true
test:
  cloud_name: "lusintoys"
  api_key: '829129926647766'
  api_secret: FQDLNL7g_yUnItOeb_1RRDxU5F4
  enhance_image_tag: true
  static_image_support: false
